language: node_js
node_js:
  - "lts/*"
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - michael.glitzos@gmail.com

before_script:
  - export CI=false

deploy:
  provider: npm
  email: michael.glitzos@gmail.com
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true